-- trades table
-- Run this in the Supabase SQL Editor to create the table.

CREATE TABLE trades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           UUID REFERENCES auth.users(id),
    item_name         TEXT NOT NULL,
    trade_direction   TEXT NOT NULL,
    buy_price         NUMERIC(10, 2) NOT NULL,
    target_sell_price NUMERIC(10, 2) NOT NULL,
    expected_profit   NUMERIC(10, 2),
    profit_margin     NUMERIC(10, 2),
    ban_end_date      TIMESTAMPTZ,
    status            TEXT NOT NULL DEFAULT 'active',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own trades" ON trades
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own trades" ON trades
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own trades" ON trades
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own trades" ON trades
    FOR DELETE USING (auth.uid() = user_id);
